name: build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  coverage:
    name: Test and publish test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: "20"
      - run: npm install
      - uses: paambaati/codeclimate-action@v2.4.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CodeClimateReporterId }}
        with:
          coverageCommand: npm run coverage
